# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onlinejudge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='onlinejudge.proto',
  package='onlinejudge',
  syntax='proto3',
  serialized_pb=_b('\n\x11onlinejudge.proto\x12\x0bonlinejudge\"-\n\x08Resource\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\xce\x01\n\x14\x43ompiledJudgeRequest\x12\x14\n\x0csubmissionID\x18\x01 \x01(\x04\x12\x12\n\ntotalCases\x18\x02 \x01(\r\x12#\n\x04lang\x18\x03 \x01(\x0e\x32\x15.onlinejudge.langCode\x12\x13\n\x0btimelimitMS\x18\x04 \x01(\r\x12\x12\n\nmemlimitKB\x18\x05 \x01(\r\x12\x14\n\x0couputlimitKB\x18\x06 \x01(\r\x12(\n\tresources\x18\x07 \x03(\x0b\x32\x15.onlinejudge.Resource\"\x90\x01\n\x15\x43ompiledJudgeResponse\x12\x12\n\ntotalCases\x18\x02 \x01(\r\x12\x0f\n\x07retCode\x18\x03 \x01(\r\x12\x11\n\truntimeMS\x18\x04 \x01(\r\x12\x11\n\tmemusedKB\x18\x05 \x01(\r\x12\x0e\n\x06stdOut\x18\x06 \x01(\t\x12\x0e\n\x06stdErr\x18\x07 \x01(\t\x12\x0c\n\x04ojid\x18\x08 \x01(\x05\"\x14\n\x12HealthCheckRequest\"\x15\n\x13HealthCheckResponse*;\n\x08langCode\x12\t\n\x05JAVA8\x10\x00\x12\t\n\x05\x43PP11\x10\x01\x12\x07\n\x03\x43\x31\x31\x10\x02\x12\x07\n\x03PY2\x10\x03\x12\x07\n\x03PY3\x10\x04\x32\xc0\x01\n\x0bOnlineJudge\x12R\n\x0bHealthCheck\x12\x1f.onlinejudge.HealthCheckRequest\x1a .onlinejudge.HealthCheckResponse\"\x00\x12]\n\x12JudgeCompiledTests\x12!.onlinejudge.CompiledJudgeRequest\x1a\".onlinejudge.CompiledJudgeResponse\"\x00\x62\x06proto3')
)

_LANGCODE = _descriptor.EnumDescriptor(
  name='langCode',
  full_name='onlinejudge.langCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JAVA8', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPP11', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C11', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PY2', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PY3', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=482,
  serialized_end=541,
)
_sym_db.RegisterEnumDescriptor(_LANGCODE)

langCode = enum_type_wrapper.EnumTypeWrapper(_LANGCODE)
JAVA8 = 0
CPP11 = 1
C11 = 2
PY2 = 3
PY3 = 4



_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='onlinejudge.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='onlinejudge.Resource.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='onlinejudge.Resource.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=79,
)


_COMPILEDJUDGEREQUEST = _descriptor.Descriptor(
  name='CompiledJudgeRequest',
  full_name='onlinejudge.CompiledJudgeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='submissionID', full_name='onlinejudge.CompiledJudgeRequest.submissionID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalCases', full_name='onlinejudge.CompiledJudgeRequest.totalCases', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='onlinejudge.CompiledJudgeRequest.lang', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timelimitMS', full_name='onlinejudge.CompiledJudgeRequest.timelimitMS', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memlimitKB', full_name='onlinejudge.CompiledJudgeRequest.memlimitKB', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ouputlimitKB', full_name='onlinejudge.CompiledJudgeRequest.ouputlimitKB', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resources', full_name='onlinejudge.CompiledJudgeRequest.resources', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=288,
)


_COMPILEDJUDGERESPONSE = _descriptor.Descriptor(
  name='CompiledJudgeResponse',
  full_name='onlinejudge.CompiledJudgeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalCases', full_name='onlinejudge.CompiledJudgeResponse.totalCases', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retCode', full_name='onlinejudge.CompiledJudgeResponse.retCode', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtimeMS', full_name='onlinejudge.CompiledJudgeResponse.runtimeMS', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memusedKB', full_name='onlinejudge.CompiledJudgeResponse.memusedKB', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdOut', full_name='onlinejudge.CompiledJudgeResponse.stdOut', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdErr', full_name='onlinejudge.CompiledJudgeResponse.stdErr', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ojid', full_name='onlinejudge.CompiledJudgeResponse.ojid', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=435,
)


_HEALTHCHECKREQUEST = _descriptor.Descriptor(
  name='HealthCheckRequest',
  full_name='onlinejudge.HealthCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=457,
)


_HEALTHCHECKRESPONSE = _descriptor.Descriptor(
  name='HealthCheckResponse',
  full_name='onlinejudge.HealthCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=480,
)

_COMPILEDJUDGEREQUEST.fields_by_name['lang'].enum_type = _LANGCODE
_COMPILEDJUDGEREQUEST.fields_by_name['resources'].message_type = _RESOURCE
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
DESCRIPTOR.message_types_by_name['CompiledJudgeRequest'] = _COMPILEDJUDGEREQUEST
DESCRIPTOR.message_types_by_name['CompiledJudgeResponse'] = _COMPILEDJUDGERESPONSE
DESCRIPTOR.message_types_by_name['HealthCheckRequest'] = _HEALTHCHECKREQUEST
DESCRIPTOR.message_types_by_name['HealthCheckResponse'] = _HEALTHCHECKRESPONSE
DESCRIPTOR.enum_types_by_name['langCode'] = _LANGCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCE,
  __module__ = 'onlinejudge_pb2'
  # @@protoc_insertion_point(class_scope:onlinejudge.Resource)
  ))
_sym_db.RegisterMessage(Resource)

CompiledJudgeRequest = _reflection.GeneratedProtocolMessageType('CompiledJudgeRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPILEDJUDGEREQUEST,
  __module__ = 'onlinejudge_pb2'
  # @@protoc_insertion_point(class_scope:onlinejudge.CompiledJudgeRequest)
  ))
_sym_db.RegisterMessage(CompiledJudgeRequest)

CompiledJudgeResponse = _reflection.GeneratedProtocolMessageType('CompiledJudgeResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMPILEDJUDGERESPONSE,
  __module__ = 'onlinejudge_pb2'
  # @@protoc_insertion_point(class_scope:onlinejudge.CompiledJudgeResponse)
  ))
_sym_db.RegisterMessage(CompiledJudgeResponse)

HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHCHECKREQUEST,
  __module__ = 'onlinejudge_pb2'
  # @@protoc_insertion_point(class_scope:onlinejudge.HealthCheckRequest)
  ))
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHCHECKRESPONSE,
  __module__ = 'onlinejudge_pb2'
  # @@protoc_insertion_point(class_scope:onlinejudge.HealthCheckResponse)
  ))
_sym_db.RegisterMessage(HealthCheckResponse)



_ONLINEJUDGE = _descriptor.ServiceDescriptor(
  name='OnlineJudge',
  full_name='onlinejudge.OnlineJudge',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=544,
  serialized_end=736,
  methods=[
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='onlinejudge.OnlineJudge.HealthCheck',
    index=0,
    containing_service=None,
    input_type=_HEALTHCHECKREQUEST,
    output_type=_HEALTHCHECKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='JudgeCompiledTests',
    full_name='onlinejudge.OnlineJudge.JudgeCompiledTests',
    index=1,
    containing_service=None,
    input_type=_COMPILEDJUDGEREQUEST,
    output_type=_COMPILEDJUDGERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONLINEJUDGE)

DESCRIPTOR.services_by_name['OnlineJudge'] = _ONLINEJUDGE

# @@protoc_insertion_point(module_scope)
