# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: onlinejudge.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

from . import onlinejudge_pb2


class OnlineJudgeBase(abc.ABC):

    @abc.abstractmethod
    async def HealthCheck(self, stream):
        pass

    @abc.abstractmethod
    async def JudgeCompiledTests(self, stream):
        pass

    def __mapping__(self):
        return {
            '/onlinejudge.OnlineJudge/HealthCheck': grpclib.const.Handler(
                self.HealthCheck,
                grpclib.const.Cardinality.UNARY_UNARY,
                onlinejudge_pb2.HealthCheckRequest,
                onlinejudge_pb2.HealthCheckResponse,
            ),
            '/onlinejudge.OnlineJudge/JudgeCompiledTests': grpclib.const.Handler(
                self.JudgeCompiledTests,
                grpclib.const.Cardinality.UNARY_UNARY,
                onlinejudge_pb2.CompiledJudgeRequest,
                onlinejudge_pb2.CompiledJudgeResponse,
            ),
        }


class OnlineJudgeStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.HealthCheck = grpclib.client.UnaryUnaryMethod(
            channel,
            '/onlinejudge.OnlineJudge/HealthCheck',
            onlinejudge_pb2.HealthCheckRequest,
            onlinejudge_pb2.HealthCheckResponse,
        )
        self.JudgeCompiledTests = grpclib.client.UnaryUnaryMethod(
            channel,
            '/onlinejudge.OnlineJudge/JudgeCompiledTests',
            onlinejudge_pb2.CompiledJudgeRequest,
            onlinejudge_pb2.CompiledJudgeResponse,
        )
